[
   {
      "body" : "Run with --tracerpc to see why the sync is failing-- probably one of the nodes has the wrong block count... ",
      "created_at" : "2015-08-13T15:15:53Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130726252",
      "id" : 130726252,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T15:15:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130726252",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/331997?v=3",
         "events_url" : "https://api.github.com/users/gavinandresen/events{/privacy}",
         "followers_url" : "https://api.github.com/users/gavinandresen/followers",
         "following_url" : "https://api.github.com/users/gavinandresen/following{/other_user}",
         "gists_url" : "https://api.github.com/users/gavinandresen/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/gavinandresen",
         "id" : 331997,
         "login" : "gavinandresen",
         "organizations_url" : "https://api.github.com/users/gavinandresen/orgs",
         "received_events_url" : "https://api.github.com/users/gavinandresen/received_events",
         "repos_url" : "https://api.github.com/users/gavinandresen/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/gavinandresen/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/gavinandresen"
      }
   },
   {
      "body" : "i had already added some code to the python scripts to output the \nblockcounts on the nodes and indeed verified that one or two nodes \nsometimes has\nthe wrong blockcount and won't sync with the others.\n\ni'll try running with tracderpc also to see if anything else pops up.\n\n  On 13/08/2015 8:16 AM, Gavin Andresen wrote:\n>\n> Run with --tracerpc to see why the sync is failing-- probably one of \n> the nodes has the wrong block count...\n>\n> Ã¢ÂÂ\n> Reply to this email directly or view it on GitHub \n> <https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130726252>.\n>\n\n",
      "created_at" : "2015-08-13T16:10:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130744748",
      "id" : 130744748,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T16:10:48Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130744748",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "I didn't see anything extra with tracerpc\n\nhowever, i additionaly verifed that the problem is not within the python \nscript by using the bitcoin-cli from the command line while the test was \nrunning to verify the blockcounts\nmanually.  They are correct, the block counts are at times not syncing.\n\nwithin the wallet.py script after the section\n# Have node0 mine a block, thus it will collect its own fee.\n\nthe block counts looks as follows:\n\n    node0, node1, node2\n    [103, 103, 103]\n\n\nthen  after mining the next 100 blocks the nodes begin to sync but \nsometimes one or two of them don't and they almost always get hung up at \n119 blocks...so the end result\nis:\n\n[203, 203, 119]\n\n\nOn 13/08/2015 8:16 AM, Gavin Andresen wrote:\n>\n> Run with --tracerpc to see why the sync is failing-- probably one of \n> the nodes has the wrong block count...\n>\n> Ã¢ÂÂ\n> Reply to this email directly or view it on GitHub \n> <https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130726252>.\n>\n\n",
      "created_at" : "2015-08-13T17:51:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130777982",
      "id" : 130777982,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T17:51:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130777982",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "Here's something that looks interesting.  When i do a \"getinfo\" on the \nnode that apparently is not syncing, the number of blocks received under \n\"errors\" shows received blocks as 203 which is correct however the \nnumber of blocks only shows as 119.    The other two nodes in the the \ntest show the correct 203 blocks for both cases.\n\n$ bitcoin-cli -rpcuser=rt -rpcpassword=rt -rpcport=12421 getinfo\n{\n   \"version\": 119900,\n   \"protocolversion\": 70002,\n   \"walletversion\": 60000,\n   \"balance\": 21.00000000,\n*\"blocks\": 119,*\n   \"timeoffset\": 0,\n   \"connections\": 4,\n   \"proxy\": \"\",\n   \"difficulty\": 4.656542373906925e-010,\n   \"testnet\": false,\n   \"keypoololdest\": 1439487755,\n   \"keypoolsize\": 2,\n   \"paytxfee\": 0.00000000,\n   \"relayfee\": 0.00001000,\n*\"errors\": \"WARNING: abnormally high number of blocks generated, 203 \nblocks rec\neived in the last 4 hours (24 expected)\"*\n}\n\nOn 13/08/2015 8:16 AM, Gavin Andresen wrote:\n>\n> Run with --tracerpc to see why the sync is failing-- probably one of \n> the nodes has the wrong block count...\n>\n> Ã¢ÂÂ\n> Reply to this email directly or view it on GitHub \n> <https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130726252>.\n>\n\n",
      "created_at" : "2015-08-13T18:01:24Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130781762",
      "id" : 130781762,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T18:01:24Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130781762",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "Looks like the node does eventually sync, i was only letting my tests \nrun about 10 mins before killing them but it seems that somewhere \nbetween 14 and 20 minutes\nthe node seems to do what it's supposed to do and sync.  But why it's \nstopping and then suddenly starting up again is a mystery since there is \nnothing in the logs other than received headers showing up.\n\nSo to sum it up:\n\n1) Some nodes seem to hang while running the wallet.py test\n2) The hung node shows the incorrect block count but no information in \nthe error/warning message in \"getinfo\"\n2) After 10 mins: the hung node shows the incorrect block count however \nthe error/warning message in \"getinfo\" shows that all blocks were received\n3) The hung node starts processing again after 14 minutes or in some \ncases almost 20 mins\n\nThe following is the part of the log where the hung node starts to \nprocess again...nothing really interesting there.\n\n2015-08-13 18:17:57 ThreadRPCServer method=getblockcount\n2015-08-13 18:17:58 ThreadRPCServer method=getblockcount\n2015-08-13 18:17:59 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:00 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:01 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:02 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:03 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:04 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:05 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:06 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:07 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:08 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:09 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:10 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:11 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:12 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:13 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:14 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:15 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:17 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:18 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:19 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:20 ThreadRPCServer method=getblockcount\n2015-08-13 18:18:20 received: headers (1378 bytes) peer=2\n2015-08-13 18:18:20 received: headers (1459 bytes) peer=2\n2015-08-13 18:18:20 received: headers (1540 bytes) peer=2\n2015-08-13 18:18:20 received: headers (1621 bytes) peer=2\n\n\n",
      "created_at" : "2015-08-13T18:56:36Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130802565",
      "id" : 130802565,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T18:56:36Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130802565",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "Lastly there is a workaround, at least as far as the python tests are \nconcerned\n\nIt appears that if one creates just 50 blocks or less at a time and then \nsync's the nodes then the scripts can move forward without problems.  \nBut create 80 or 100 blocks and the\nnodes can then get hung for a while, up to 20 mins before syncing. (this \nhanging of the node is  happening when running  wallet.py and also \nwalletbackup.py )\n\n\n",
      "created_at" : "2015-08-13T22:46:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130870277",
      "id" : 130870277,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T22:46:48Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130870277",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "Very odd that syncing long chains is misbehaving on Windows -- that's definitely a bug.\r\n\r\nUnfortunately, I don't think we have any developers with a very deep knowledge of the syncing process AND a Windows development environment in which they might be able to debug the problem.\r\n",
      "created_at" : "2015-08-13T22:55:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130871846",
      "id" : 130871846,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T22:55:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130871846",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/331997?v=3",
         "events_url" : "https://api.github.com/users/gavinandresen/events{/privacy}",
         "followers_url" : "https://api.github.com/users/gavinandresen/followers",
         "following_url" : "https://api.github.com/users/gavinandresen/following{/other_user}",
         "gists_url" : "https://api.github.com/users/gavinandresen/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/gavinandresen",
         "id" : 331997,
         "login" : "gavinandresen",
         "organizations_url" : "https://api.github.com/users/gavinandresen/orgs",
         "received_events_url" : "https://api.github.com/users/gavinandresen/received_events",
         "repos_url" : "https://api.github.com/users/gavinandresen/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/gavinandresen/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/gavinandresen"
      }
   },
   {
      "body" : "Such a long delay sounds like the block download tineout triggering,\ncausing it to be requestes from another peer? Just a guess.\n",
      "created_at" : "2015-08-13T22:58:24Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130872181",
      "id" : 130872181,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-13T22:58:24Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130872181",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=3",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "body" : "If wallet.py and walletbackup.py are breaking from time to time it could be because both tests do a shutdown and restart of (at least one) node (https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/wallet.py#L182). I once also had issues with the wait_bitcoinds() command.",
      "created_at" : "2015-08-14T06:45:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130995139",
      "id" : 130995139,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-14T06:45:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/130995139",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "the problem happens early on and before any shuydown/restart.\n\nOn 13/08/2015 11:45 PM, Jonas Schnelli wrote:\n>\n> If wallet.py and walletbackup.py are breaking from time to time it \n> could be because both tests do a shutdown and restart of (at least \n> one) node \n> (https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/wallet.py#L182). \n> I once also had issues with the wait_bitcoinds() command.\n>\n> Ã¢ÂÂ\n> Reply to this email directly or view it on GitHub \n> <https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-130995139>.\n>\n\n",
      "created_at" : "2015-08-14T07:06:53Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-131000035",
      "id" : 131000035,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-14T07:06:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/131000035",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "@ptschip: did you already try to see if some informations are present in the nodes debug.log(s)?",
      "created_at" : "2015-08-17T15:31:12Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-131863404",
      "id" : 131863404,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-17T15:31:12Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/131863404",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "yes, if you read through the bug report you'll see all that...On \n17/08/2015 8:31 AM, Jonas Schnelli wrote:\n>\n> @ptschip <https://github.com/ptschip>: did you already try to see if \n> some informations are present in the nodes debug.log(s)?\n>\n> Ã¢ÂÂ\n> Reply to this email directly or view it on GitHub \n> <https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-131863404>.\n>\n\n",
      "created_at" : "2015-08-17T16:02:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-131873625",
      "id" : 131873625,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-08-17T16:02:47Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/131873625",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "@ptschip Is the issue fixed in current master?",
      "created_at" : "2015-09-13T23:07:09Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-139927422",
      "id" : 139927422,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-09-13T23:07:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/139927422",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=3",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "body" : "After comiling with libevent 2.0.22, i ran the wallet.py test 10 times\nand nodes failed to sync on five of the tests, always at the same place\nas before: where we mine 100 blocks and then try to sync. \n\nUnfortunately, Libevent most definitely does not fix this issue on\nNative Windows\n\n\n\nOn 13/09/2015 4:07 PM, MarcoFalke wrote:\n>\n> @ptschip <https://github.com/ptschip> Is the issue fixed in current\n> master?\n>\n> Ã¢ÂÂ\n> Reply to this email directly or view it on GitHub\n> <https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-139927422>.\n>\n\n",
      "created_at" : "2015-09-14T01:50:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-139938935",
      "id" : 139938935,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2015-09-14T01:50:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/139938935",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/12862928?v=3",
         "events_url" : "https://api.github.com/users/ptschip/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ptschip/followers",
         "following_url" : "https://api.github.com/users/ptschip/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ptschip/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ptschip",
         "id" : 12862928,
         "login" : "ptschip",
         "organizations_url" : "https://api.github.com/users/ptschip/orgs",
         "received_events_url" : "https://api.github.com/users/ptschip/received_events",
         "repos_url" : "https://api.github.com/users/ptschip/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ptschip/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ptschip/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ptschip"
      }
   },
   {
      "body" : "There are plans for using it, but libevent has nothing to do with the P2P protocol implementation at the moment, so it makes sense that that didn't change anything.\r\n",
      "created_at" : "2016-04-28T11:14:58Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6554#issuecomment-215391754",
      "id" : 215391754,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6554",
      "updated_at" : "2016-04-28T11:14:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/215391754",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
