[
   {
      "body" : "~~Confirmed (but maybe also a different error than @apoelstra, but probably same root).\r\nJust tested with a corrupted regtest wallet and got:~~\r\n```\r\nUsing wallet wallet.dat\r\ninit message: Verifying wallet...\r\nCDBEnv::Open: LogDir=<snip>/regtest/database ErrorFile=/<snip>/db.log\r\nFailed to rename wallet.dat to wallet.1440416498.bak\r\nError: \r\nError: \r\nShutdown: In progress...\r\n```\r\n\r\n~~From the BDB docs:~~\r\n> The DB->rename() method may not be called after calling the DB->open() method on any DB handle. If the DB->open() method has already been called on a DB handle, close the existing handle and create a new one before calling DB->rename().\r\n\r\n~~If I follow the code correctly, we do a `Open` before we try the `DB->rename()`.~~\r\n\r\n~~Will try to write a fix.~~",
      "created_at" : "2015-08-24T11:57:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6582#issuecomment-134165769",
      "id" : 134165769,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6582",
      "updated_at" : "2015-08-24T12:34:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/134165769",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "Sorry. Reported wrong.\r\nWorks for me.\r\n\r\nIf the `wallet.dat` if fully corrupted like @apoelstra \"echo\" example, a rename is not possible (results error 22 = Invalid argument). If a salvaging is possible, the rename does work independent from current working directory.\r\nIf the rename locations are faulty (on some os), it is very likely a upstream issue because our code calls: \r\n```\r\nint result = dbenv.dbenv->dbrename(NULL, filename.c_str(), NULL,\r\n                                       newFilename.c_str(), DB_AUTO_COMMIT);\r\n```",
      "created_at" : "2015-08-24T12:41:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6582#issuecomment-134180337",
      "id" : 134180337,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6582",
      "updated_at" : "2015-08-24T12:41:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/134180337",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "@jonasschnelli it's possible I misunderstood the problem because I replaced `dbrename` with a cstdio `rename` to get the errno output. Then I assumed `rename`'s \"file not found\" problem was the same one that `dbrename` was giving me (which was actually \"database too corrupted to be opened\").\r\n\r\nDoes that explain both our observations?",
      "created_at" : "2015-08-24T16:16:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6582#issuecomment-134277587",
      "id" : 134277587,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6582",
      "updated_at" : "2015-08-24T17:08:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/134277587",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1351933?v=3",
         "events_url" : "https://api.github.com/users/apoelstra/events{/privacy}",
         "followers_url" : "https://api.github.com/users/apoelstra/followers",
         "following_url" : "https://api.github.com/users/apoelstra/following{/other_user}",
         "gists_url" : "https://api.github.com/users/apoelstra/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/apoelstra",
         "id" : 1351933,
         "login" : "apoelstra",
         "organizations_url" : "https://api.github.com/users/apoelstra/orgs",
         "received_events_url" : "https://api.github.com/users/apoelstra/received_events",
         "repos_url" : "https://api.github.com/users/apoelstra/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/apoelstra/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/apoelstra/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/apoelstra"
      }
   },
   {
      "body" : "@apoelstra: my tests did show me that `dbrename` will response with `invalid argument` if the database is \"too corrupted\". `File not found` is also possible, but only happened in my test if i have used a non-existing filename.\r\nThe filename is relative because `dbrename` assume that we already have initialized a db context (with path/file, etc.).",
      "created_at" : "2015-08-26T11:54:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6582#issuecomment-134962985",
      "id" : 134962985,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6582",
      "updated_at" : "2015-08-26T11:54:02Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/134962985",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "Looks like the user changed code which may have resulted in this problem, the issue is inactive, so closing.\r\n",
      "created_at" : "2015-11-24T09:21:28Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6582#issuecomment-159205048",
      "id" : 159205048,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6582",
      "updated_at" : "2015-11-24T09:21:28Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/159205048",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
