{
   "assignee" : null,
   "body" : "Not sure I completely understand this yet, so opening an issue for now:\r\n\r\nAfter #5677, I believe it is now the case that the rpc tests may fail if there's inactivity for more than 30 seconds after opening a connection.  I'm getting repeatable failures locally on some of the longer-running tests (such as bipdersig.py), which I seem to be able to fix by either increasing the rpctimeout on all the nodes in the test, or by keeping the rpc connections warm with more rpc calls.\r\n\r\nI think some travis jobs may be failing for this reason as well: https://travis-ci.org/bitcoin/bitcoin/builds/79514930\r\n\r\nI'm not sure what the right solution is -- should the rpc test framework change somehow to allow for the connection to be re-established?  Or should we just be defaulting the timeout to a longer value in the tests that need it? ",
   "closed_at" : "2015-10-20T13:40:06Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
      "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
      "followers_url" : "https://api.github.com/users/laanwj/followers",
      "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
      "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/laanwj",
      "id" : 126646,
      "login" : "laanwj",
      "organizations_url" : "https://api.github.com/users/laanwj/orgs",
      "received_events_url" : "https://api.github.com/users/laanwj/received_events",
      "repos_url" : "https://api.github.com/users/laanwj/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/laanwj"
   },
   "comments" : 9,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6655/comments",
   "created_at" : "2015-09-09T21:35:24Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6655/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/6655",
   "id" : 105689230,
   "labels" : [
      {
         "color" : "006b75",
         "name" : "P2P",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/P2P"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6655/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 6655,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Issues in master after libevent merge",
   "updated_at" : "2015-10-20T13:40:06Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6655",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/7463573?v=3",
      "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
      "followers_url" : "https://api.github.com/users/sdaftuar/followers",
      "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
      "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/sdaftuar",
      "id" : 7463573,
      "login" : "sdaftuar",
      "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
      "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
      "repos_url" : "https://api.github.com/users/sdaftuar/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/sdaftuar"
   }
}
