{
   "assignee" : null,
   "body" : "client version: 0.4.0-beta\r\nos: windows7 64bit\r\n\r\nMy bitcoin's datadir folder is symbolic link to folder on removable drive (all of them is ntfs file system), when i use latest version from bitcoin.org it fail with empty error message box and crashed. In debug.log put 2 messages:\r\n\r\n************************\r\nEXCEPTION: N5boost11filesystem316filesystem_errorE       \r\nboost::filesystem::create_directory: ÃÂÃÂµÃÂ²ÃÂ¾ÃÂ·ÃÂ¼ÃÂ¾ÃÂ¶ÃÂ½ÃÂ¾ ÃÂÃÂ¾ÃÂ·ÃÂ´ÃÂ°ÃÂÃÂ ÃÂÃÂ°ÃÂ¹ÃÂ», ÃÂÃÂ°ÃÂº ÃÂºÃÂ°ÃÂº ÃÂ¾ÃÂ½ ÃÂÃÂ¶ÃÂµ ÃÂÃÂÃÂÃÂµÃÂÃÂÃÂ²ÃÂÃÂµÃÂ: \"C:\\Users\\rpman\\AppData\\Roaming\\Bitcoin\"       \r\nC:\\Program Files (x86)\\Bitcoin\\bitcoin.exe in AppInit()       \r\n\r\n************************\r\nIt's russian localisation, translated message is:\r\n>> Can not create file because it already exists:\r\n\r\nIf remove symbolic link and make local copy, program starts and work fine.\r\nAlso -datadir command line argument to removable drive helps too.",
   "closed_at" : "2011-09-24T14:44:45Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/331997?v=3",
      "events_url" : "https://api.github.com/users/gavinandresen/events{/privacy}",
      "followers_url" : "https://api.github.com/users/gavinandresen/followers",
      "following_url" : "https://api.github.com/users/gavinandresen/following{/other_user}",
      "gists_url" : "https://api.github.com/users/gavinandresen/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/gavinandresen",
      "id" : 331997,
      "login" : "gavinandresen",
      "organizations_url" : "https://api.github.com/users/gavinandresen/orgs",
      "received_events_url" : "https://api.github.com/users/gavinandresen/received_events",
      "repos_url" : "https://api.github.com/users/gavinandresen/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/gavinandresen/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/gavinandresen"
   },
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/529/comments",
   "created_at" : "2011-09-24T06:33:58Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/529/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/529",
   "id" : 1729039,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/529/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 529,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Starting fail with symbolic link datadir in c:\\users\\...",
   "updated_at" : "2011-09-24T14:44:45Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/529",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/938140?v=3",
      "events_url" : "https://api.github.com/users/rPman/events{/privacy}",
      "followers_url" : "https://api.github.com/users/rPman/followers",
      "following_url" : "https://api.github.com/users/rPman/following{/other_user}",
      "gists_url" : "https://api.github.com/users/rPman/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/rPman",
      "id" : 938140,
      "login" : "rPman",
      "organizations_url" : "https://api.github.com/users/rPman/orgs",
      "received_events_url" : "https://api.github.com/users/rPman/received_events",
      "repos_url" : "https://api.github.com/users/rPman/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/rPman/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/rPman/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/rPman"
   }
}
