{
   "assignee" : null,
   "assignees" : [],
   "body" : "I'm trying to call bitcoind sendtoaddress with params :\n\n18et8yw71yfxsQz99c5sHHEgYtR32kkfw 0.15161962\n\nand there is an exception \"(500) Internal Server Error.\"\n\nThe wallet has sufficient funds ~30 bitcoins\nThe same call to different address works good\nThe same call with different amount (0.001bitcoin) works good\nIt started to fail with internal errors since 0.12.11 bitcoin core version and qt-5.5.0\nI don't understand why only this call failed ?\n\nI set the fee to 0.0002 before calling sendtoaddress , the problem is that the call sendtoaddress one time works and sometimes return internal error, Is there some kind of log ? \n",
   "closed_at" : "2017-05-18T12:45:32Z",
   "closed_by" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/863730?v=3",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   },
   "comments" : 9,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8211/comments",
   "created_at" : "2016-06-16T19:43:19Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8211/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/8211",
   "id" : 160743496,
   "labels" : [
      {
         "color" : "0052cc",
         "default" : false,
         "id" : 98279177,
         "name" : "RPC/REST/ZMQ",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/RPC/REST/ZMQ"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8211/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 8211,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Bitcoind Internal Server Error",
   "updated_at" : "2017-05-18T12:45:32Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8211",
   "user" : {
      "avatar_url" : "https://avatars3.githubusercontent.com/u/6370865?v=3",
      "events_url" : "https://api.github.com/users/macdasi/events{/privacy}",
      "followers_url" : "https://api.github.com/users/macdasi/followers",
      "following_url" : "https://api.github.com/users/macdasi/following{/other_user}",
      "gists_url" : "https://api.github.com/users/macdasi/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/macdasi",
      "id" : 6370865,
      "login" : "macdasi",
      "organizations_url" : "https://api.github.com/users/macdasi/orgs",
      "received_events_url" : "https://api.github.com/users/macdasi/received_events",
      "repos_url" : "https://api.github.com/users/macdasi/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/macdasi/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/macdasi/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/macdasi"
   }
}
