{
   "assignee" : null,
   "body" : "`blockchain.py` is failing on master and 0.12, due to a subtle merge conflict when #7194 was merged.\r\n\r\n@laanwj Needs backport",
   "closed_at" : "2016-01-18T15:01:18Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
      "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
      "followers_url" : "https://api.github.com/users/laanwj/followers",
      "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
      "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/laanwj",
      "id" : 126646,
      "login" : "laanwj",
      "organizations_url" : "https://api.github.com/users/laanwj/orgs",
      "received_events_url" : "https://api.github.com/users/laanwj/received_events",
      "repos_url" : "https://api.github.com/users/laanwj/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/laanwj"
   },
   "comments" : 4,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7373/comments",
   "created_at" : "2016-01-18T14:25:15Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7373/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/7373",
   "id" : 127236229,
   "labels" : [
      {
         "color" : "d4c5f9",
         "name" : "Tests",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7373/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 7373,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/7373.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/7373",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/7373.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/7373"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "[Tests] Fix error in blockchain.py introduced in merge",
   "updated_at" : "2016-01-18T15:01:18Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7373",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/7463573?v=3",
      "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
      "followers_url" : "https://api.github.com/users/sdaftuar/followers",
      "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
      "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/sdaftuar",
      "id" : 7463573,
      "login" : "sdaftuar",
      "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
      "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
      "repos_url" : "https://api.github.com/users/sdaftuar/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/sdaftuar"
   }
}
