{
   "assignee" : null,
   "body" : "I have been running a 5gh/s BFL miner for quite some time using bfgminer 3.10.0 and bitcoin core 0.9.3. both running on the same host (Ubuntu 14.04) with  no problems for quite some time. This issue began only after upgrading to bitcoin core 0.10.0rc1. I am not a developer so I'm not sure what's causing my issue. It appears that after just over 1 hour the miner loses connection and becomes unable to re-connect. I am able to replicate this issue fairly consistently. Restarting either bitcoind -or- bfgminer resumes normal operation for another hour and then it fails again. It should also be noted that if I run my previous bitcoind (0.9.3) the issue does not seem to occur. I'm happy to provide any other details you may need and I'm willing to test out any possible fixes. I can also grant shell access if absolutely necessary, but I would prefer not to.\r\n\r\nHere are the logs from bfgminer and bitcoind:\r\nhttps://drive.google.com/file/d/0B6YbMZIt-hIjNUlPaEpoYVktSkE/view?usp=sharing\r\nhttps://drive.google.com/file/d/0B6YbMZIt-hIjTmx3dlJNXzhiV1E/view?usp=sharing\r\n\r\nThank You,\r\nJohn\r\n\r\n",
   "closed_at" : "2014-12-25T13:13:46Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/8405851?v=3",
      "events_url" : "https://api.github.com/users/john-yonn/events{/privacy}",
      "followers_url" : "https://api.github.com/users/john-yonn/followers",
      "following_url" : "https://api.github.com/users/john-yonn/following{/other_user}",
      "gists_url" : "https://api.github.com/users/john-yonn/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/john-yonn",
      "id" : 8405851,
      "login" : "john-yonn",
      "organizations_url" : "https://api.github.com/users/john-yonn/orgs",
      "received_events_url" : "https://api.github.com/users/john-yonn/received_events",
      "repos_url" : "https://api.github.com/users/john-yonn/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/john-yonn/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/john-yonn/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/john-yonn"
   },
   "comments" : 3,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/5539/comments",
   "created_at" : "2014-12-25T00:34:54Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/5539/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/5539",
   "id" : 52841490,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/5539/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 5539,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Problems with Solo Mining after upgrading from 0.9.3 to 0.10.0rc1",
   "updated_at" : "2014-12-25T13:13:46Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/5539",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/8405851?v=3",
      "events_url" : "https://api.github.com/users/john-yonn/events{/privacy}",
      "followers_url" : "https://api.github.com/users/john-yonn/followers",
      "following_url" : "https://api.github.com/users/john-yonn/following{/other_user}",
      "gists_url" : "https://api.github.com/users/john-yonn/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/john-yonn",
      "id" : 8405851,
      "login" : "john-yonn",
      "organizations_url" : "https://api.github.com/users/john-yonn/orgs",
      "received_events_url" : "https://api.github.com/users/john-yonn/received_events",
      "repos_url" : "https://api.github.com/users/john-yonn/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/john-yonn/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/john-yonn/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/john-yonn"
   }
}
